###################################################
# Parameters 
###################################################
# output different prompts for debugging purpose
VERBOSE: 0

DEVICE: cuda

FLOAT_PRECISION: 32
# number of initializations
N_BATCH: 100
# 1 to save the data to DATA_PATH
SAVE_DATA: 1

# Time step in s
DT: 0.001
# total simulation time in s
DURATION: 5.0
# time to start saving simulation files
T_STEADY: 0.0
# Saving to files every T_WINDOW
T_WINDOW: .25

# record only endpoint
REC_LAST_ONLY: 1

##########################################
# Parameters for the stimulus presentation
##########################################
# stimulus as a cosine shape
# time for stimulus onset in s 
T_STIM: [1.0, 1.5]
# amplitude of the 1st stimulus
I0: [1.0]
# amplitude of the 2nd stimulus
T_DIST: [2.5, 3.0]
# amplitude of the 2nd stimulus [mean, var]
I1: [0.0, 0.0]

# Phase of the 1st stimulus
PHI0: 0.0
PHI1: 90.0
# Tuning of the 1st stimulus
SIGMA0: 1.0
SIGMA1: 0.25
# Phase difference between 1st/2nd stimuli
DPHI: 0.25

##########################################
# Network parameters
##########################################
# number of populations
N_POP: 1
# number of neurons
N_NEURON: 1000
# number of average presynaptic input (set to 1 if all to all)
K: 1.0
# fraction of neuron in each population (must sum to 1)
frac: [1.0]

##########################################
# Network Dynamic
##########################################
# Transfert Function
# set to 0 for threshold linear, 1 for sigmoid
TF_TYPE: erfc

# Dynamics of the rates
# set to 0 if instantaneous rates, 1 if exponentially decaying
RATE_DYN: 1
# rate time constants
TAU: [.020]

# Dynamics of the recurrent inputs
# set to 0 if instantaneous, 1 if exponentially decaying
SYN_DYN: 0
# Synaptic time constants for each population
TAU_SYN: [.002]

# Adding NMDA currents
IF_NMDA: 0
# NMDA time constants
TAU_NMDA: [0.2]

# Feedforward inputs dynamics
# set to 0 for instantaneous, 1 to exp decay, 2 adds gaussian noise
FF_DYN: 2
# FF time constants
TAU_FF: [4.]
# Variance of the noise
VAR_FF: [30000.]
# Threshold dynamics
# set to 0 constant thresholds, 1 to add adaptative thresholds
THRESH_DYN: 0
# threshold
THRESH: [15.0]
# threshold time constants
TAU_THRESH: [0.08]

# Network's gain
GAIN: 1.0

# Synaptic strengths           
Jab: [-2.75]
# External inputs strengths
Ja0: [14.0]
# External rate
M0: 1.0

# To add an attentional switch
# if BUMP_SWITCH[i] == 1 it sets Iext[i] to zero before stimulus presentation
BUMP_SWITCH: [1]

####################
# Plasticity
####################
# adds short term plasticity
IF_STP: 0

##############
# Connectivity
##############
# load connectivity matrix
LOAD_MAT: 0
# save connectivity matrix
SAVE_MAT: 1

# seed for connectivity None or float
SEED: 1

# STRUCTURE can be 'all', 'all_cos', 'cos', 'spec_cos'
# By default the matrix is a random sparse matrix
# 'cos' gives a sparse matrix with strong cosine structure
# 'spec_cos' gives a sparse matrix with weak cosine structure
# 'all' gives an all to all matrix
# 'all_cos' gives an all to all with cosine shape

# sets probabilities of connections' shape
CONNECTIVITY: 'all2all'
STRUCTURE: ['cosine']
# strength of the asymmetries if all to all
SIGMA: [0.0]
# tuning of the recurrent connections
KAPPA: [0.4]
# phase of the connectivity
PHASE: 180.0
