###################################################
# Parameters 
###################################################
# output different prompts for debugging purpose
VERBOSE: 1
# device to be used cuda or cpu
DEVICE: cuda
# float precision
FLOAT_PRECISION: 32
# 1 to save the data to DATA_PATH
SAVE_DATA: 1

# Time step in s
DT: 0.01
# total simulation time in s
DURATION: 6.0
# time to start saving simulation files
T_STEADY: 0.5
# Saving to files every T_WINDOW
T_WINDOW: 0.5

# record only endpoint
REC_LAST_ONLY: 0

##########################################
# Parameters for the stimulus presentation
##########################################
# stimulus as a cosine shape
# time for stimulus onset in s 
T_STIM: [1.0, 2.0]
# amplitude of the 1st stimulus
I0: [0.01, 0.0]
# amplitude of the 2nd stimulus
T_DIST: [35, 45]
# amplitude of the 2nd stimulus [mean, var]
I1: [0.01, 0.0]
T_CUE: [5.5, 6.0]
T_TEST: [3.0, 5.0]

# Phase of the stimuli
PHI0: 1.0
PHI1: 1.0
# Tuning of the stimuli
SIGMA0: 1.0
SIGMA1: 0.25

##########################################
# Network parameters
##########################################
# number of populations
N_POP: 2
# number of neurons
N_NEURON: 1000
# number of average presynaptic input (set to 1 if all to all)
K: 50.0
# fraction of neuron in each population (must sum to 1)
frac: [0.75, 0.25]

##########################################
# Network Dynamic
##########################################
# Transfert Function
# set to 0 for threshold linear, 1 for sigmoid
TF_TYPE: 'relu'

# Dynamics of the rates
# set to 0 if instantaneous rates, 1 if exponentially decaying
RATE_DYN: 0
# rate time constants
TAU: [.020, 0.020]

# Dynamics of the recurrent inputs
# set to 0 if instantaneous, 1 if exponentially decaying
SYN_DYN: 1
# Synaptic time constants for each population
TAU_SYN: [.4, 0.2]

# Adding NMDA currents
IF_NMDA: 0
# NMDA time constants
TAU_NMDA: [0.2, 0.2]

# Feedforward inputs dynamics
# set to 0 for instantaneous, 1 to exp decay, 2 adds gaussian noise
FF_DYN: 2
# FF time constants
TAU_FF: [4.]
# Variance of the noise
VAR_FF: [1.0, 1.0]
# Threshold dynamics
# set to 0 constant thresholds, 1 to add adaptative thresholds
THRESH_DYN: 0
# threshold
THRESH: [15.0, 15.0]
# threshold time constants
TAU_THRESH: [1., 1.]

# Network's gain
GAIN: 1.0

# Jab: [1., -1.35, 1.25, -2.0]
# Ja0: [0.25, 0.175]

# Synaptic strengths           
Jab: [1.0, -1.5, 1, -1]
# External inputs strengths
Ja0: [2.0, 1.0]
# External rate
M0: 2.0

# To add an attentional switch
# if BUMP_SWITCH[i] == 1 it sets Iext[i] to zero before stimulus presentation
BUMP_SWITCH: [0, 0]

####################
# Plasticity
####################
# adds short term plasticity
IF_STP: 0

##############
# Connectivity
##############
# seed for connectivity None or float
SEED: 1

# STRUCTURE can be 'all', 'all_cos', 'cos', 'spec_cos'
# By default the matrix is a random sparse matrix
# 'cos' gives a sparse matrix with strong cosine structure
# 'spec_cos' gives a sparse matrix with weak cosine structure
# 'all' gives an all to all matrix
# 'all_cos' gives an all to all with cosine shape

# sets probabilities of connections' shape
CONNECTIVITY: 'sparse'
STRUCTURE: ['None', 'None', 'None', 'None']

# create uniformly distributed wells
WELLS: [0.0, 0.0, 0.0, 0.0]
# strength of the asymmetries if all to all
SIGMA: [0.0, 0.0, 0.0, 0.0]
# tuning of the recurrent connections
KAPPA: [2.0, 0.0, 0.0, 0.0]
# phase of the connectivity
PHASE: 180.0

##########
# Low rank
##########
RANK: 2.0
# covariance
LR_COV: 0.0

