###############################################
# Parameters
###############################################
# output different prompts for debugging purpose
VERBOSE: 0
# device to be used cuda or cpu
DEVICE: 'cuda:1'
# float precision
FLOAT_PRECISION: 32

######################################
# Simulation Parameters
#####################################
# Number of batches (ie initializations)
N_BATCH: 1
# Time step in s
DT: 0.02
# total simulation time in s
DURATION: 10.0

# time to start saving simulation files
T_STEADY: 2.0
# Saving to files every T_WINDOW
T_WINDOW: 0.1

##########################################
# Parameters for the stimulus presentation
##########################################
# stimulus as a cosine shape
TASK: 'odr'
# # time for stimuli onset in s
T_STIM_ON: [1.0, 4.0]
# # # time for stimuli offset in s
T_STIM_OFF: [2.0, 5.0]
# stimuli strengths
I0: [1.0, -5.0]
# stimuli phases
PHI0: [180.0, 180]
# stimuli phases
PHI1: [180.0, 180.0]
# stimuli tuning
SIGMA0: [1.0, 0.0]

#########################################
# Network parameters
##########################################
# number of populations
N_POP: 2
# number of neurons
N_NEURON: 1000
# number of average presynaptic input (set to 1 if all to all)
K: 250.0

FRAC_K: 0
# fraction of neuron in each population (must sum to 1)
frac: [0.75, 0.25]

##########################################
# Transfert Function for rate model
##########################################
# set to 0 for threshold linear, 1 for sigmoid
TF_TYPE: 'relu'
# threshold
THRESH: [0.0, 0.0]

##########################################
# Dynamics of the rates
##########################################
# set to 0 if instantaneous rates, 1 if exponentially decaying
RATE_DYN: 0
# rate time constants
TAU: [0.4, 0.4]

# adding rate noise for diffusion
RATE_NOISE: 0
VAR_RATE: 1.0

##########################################
# Dynamics of the recurrent inputs
##########################################
# set to 0 if instantaneous, 1 if exponentially decaying
SYN_DYN: 1
# Synaptic time constants for each population
TAU_SYN: [.3, .2]

##########################################
# NMDA currents
#########################################
IF_NMDA: 0
R_NMDA: 1
TAU_NMDA: [1.0, 1.0]

##########################################
# Adaptation currents
#########################################
IF_ADAPT: 0
A_ADAPT: 1.0
TAU_ADAPT: [1.0, 1.0]

####################
# Plasticity
####################
IF_STP: 1
USE: 0.03
TAU_FAC: 0.5
TAU_REC: 0.2
J_STP: 1.0
STP_TYPE: 'markram'

##########################################
# Feedforward inputs
##########################################
# External inputs strengths
Ja0: [2.0, 1.0]
# External rate
M0: 1.0
# Variance of the noise
VAR_FF: [2.0, 2.0]
##########################################
# Synaptic strengths
##########################################
# Network's gain
GAIN: 1.0
# Synaptic strengths
Jab: [1.0, -1.5, 1, -1]

##############
# Connectivity
##############
# seed for connectivity None or float
SEED: 'None'
# CON_TYPE can be 'all2all' or 'sparse'
CON_TYPE: 'sparse'
# PROBA_TYPE can be 'cosine', 'cosine_spec' or 'lr'
PROBA_TYPE: ['None', 'None', 'None', 'None']
# strength of the asymmetries if all to all
SIGMA: [0.0, 0.0, 0.0, 0.0]
# tuning of the recurrent connections
KAPPA: [0.0, 0.0, 0.0, 0.0]
# phase of the connectivity
PHASE: 0.0

###############
# ODR TRAINING
###############
TRAIN_SCALE: 'none'
ODR_TRAIN: 1
RANDOM_DELAY: 1

TRAIN_EI: 0
IS_TRAIN: [0, 0, 0, 0]

CLAMP: 1
DROP_RATE: 0.0
MAX_DELAY: 6.0
MIN_DELAY: 0.0
