###############################################
# Parameters
###############################################
# output different prompts for debugging purpose
VERBOSE: 0
# device to be used cuda or cpu
DEVICE: 'cuda:1'
# float precision
FLOAT_PRECISION: 32

######################################
# Simulation Parameters
#####################################
# Number of batches (ie initializations)
N_BATCH: 1
# Time step in s
DT: 0.02
# total simulation time in s
DURATION: 6.0
# time to start saving simulation files
T_STEADY: 1.0
# Saving to files every T_WINDOW
T_WINDOW: 0.1

##########################################
# Parameters for the stimulus presentation
##########################################
# stimulus as a cosine shape
TASK: 'odr'
# # time for stimuli onset in s
T_STIM_ON: [1.0, 4.0]
# # # time for stimuli offset in s
T_STIM_OFF: [2.0, 5.0]
# stimuli strengths
I0: [1.0, -10]
# stimuli phases
PHI0: [180.0, 180]
# stimuli phases
PHI1: [180.0, 180.0]
# stimuli tuning
SIGMA0: [1.0, 0.0]

##########################################
## Reward go
##########################################
IF_RL: 0
RWD: 2
##########################################
# Network parameters
##########################################
# number of populations
N_POP: 2
# number of neurons
N_NEURON: 1000
# number of average presynaptic input (set to 1 if all to all)
K: 100.0
# fraction of neuron in each population (must sum to 1)
frac: [0.5, 0.5]

##########################################
# Voltage Dynamics for LIF model
##########################################
# Threshold in mV
V_THRESH: -50.0
# Resting potential in mV
V_REST: -70.0

##########################################
# Transfert Function for rate model
##########################################
# set to 0 for threshold linear, 1 for sigmoid
TF_TYPE: 'relu'
# threshold
THRESH: [1.0, 1.0]

##########################################
# Dynamics of the rates
##########################################
# set to 0 if instantaneous rates, 1 if exponentially decaying
RATE_DYN: 0
# rate time constants
TAU: [0.4, 0.2]
RATE_NOISE: 0

##########################################
# Dynamics of the recurrent inputs
##########################################
# set to 0 if instantaneous, 1 if exponentially decaying
SYN_DYN: 1
# Synaptic time constants for each population
TAU_SYN: [.2, .1]

##########################################
# NMDA currents
#########################################
IF_NMDA: 1
R_NMDA: 1
TAU_NMDA: [1.0, 1.0]

####################
# Plasticity
####################
IF_STP: 1
USE: 0.03
TAU_FAC: 0.5
TAU_REC: 0.2
J_STP: 30.0
STP_TYPE: 'markram'

##########################################
# Feedforward inputs
##########################################
LIVE_FF_UPDATE: 0
# External inputs strengths
Ja0: [2.0, 1.0]
# External rate
M0: 1.0
# Variance of the noise
VAR_FF: [1.0, 1.0]
# To add an attentional switch
# if BUMP_SWITCH[i] == 1 it sets Iext[i] to zero before stimulus presentation
BUMP_SWITCH: [0, 0]

##########################################
# Synaptic strengths
##########################################
# Network's gain
GAIN: 1.0
# Synaptic strengths
Jab: [1.0, -1.5, 1, -1]
# Batching Jab
IF_BATCH_J: 0

##############
# Connectivity
##############
# None, full, semi
SPARSE: 0
# seed for connectivity None or float
SEED: 'None'
# CON_TYPE can be 'all2all' or 'sparse'
CON_TYPE: 'sparse'
# PROBA_TYPE can be 'cosine', 'cosine_spec' or 'lr'
PROBA_TYPE: ['None', 'None', 'None', 'None']
# strength of the asymmetries if all to all
SIGMA: [0.0, 0.0, 0.0, 0.0]
# tuning of the recurrent connections
KAPPA: [0.0, 0.0, 0.0, 0.0]
# phase of the connectivity
PHASE: 0.0

##########
# Low rank
##########
LR_TRAIN: 0

LR_READOUT: 1
LR_CLASS: 1
LR_BIAS: 1
LR_FIX_READ: 1

LR_MASK: 0
LR_NORM: 0
LR_CLAMP: 1
LR_KAPPA: 1
LR_MN: 0

ODR_TRAIN: 1
CLAMP: 0
DROP_RATE: 0.5
TRAIN_EI: 0

RANK: 0
LR_MEAN: [0.0]
LR_COV: [[1.0, 0.9, 0.0, 0.0],[0.9, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.9], [0.0, 0.0, 0.9, 1.0]]
