###############################################
# Parameters
###############################################
# output different prompts for debugging purpose
VERBOSE: 0
# device to be used cuda or cpu
DEVICE: 'cuda:1'
# float precision
FLOAT_PRECISION: 32

######################################
# Simulation Parameters
#####################################
# Number of batches (ie initializations)
N_BATCH: 1
# Time step in s
DT: 0.02
DURATION: 10
# total simulation time in s
# time to start saving simulation files
T_STEADY: 2.0
# Saving to files every T_WINDOW
T_WINDOW: 0.1

##########################################
# Parameters for the stimulus presentation
##########################################
# stimulus as a cosine shape
TASK: 'dual'
# time for stimuli onset in s
T_STIM_ON: [1.0, 3.0, 5.0, 5.5, 7.0]
# time for stimuli offset in s
T_STIM_OFF: [2.0, 4.0, 5.5, 6.0, 8.0]
# stimuli strengths
I0: [1.0, 0.0, 0.0, 0.0, 0.0]
# stimuli phases
PHI0: [180.0, 90.0, 0.0, 0.0, 0.0]
# stimuli phases
PHI1: [180.0, 90.0, 0.0, 0.0, 0.0]
# stimuli tuning
SIGMA0: [1.0, 1.0, 1.0, 1.0, 1.0]

##########################################
# Network parameters
##########################################
# number of populations
N_POP: 2
# number of neurons
N_NEURON: 1000
# number of average presynaptic input (set to 1 if all to all)
K: 100.0
FRAC_K: 0
# fraction of neuron in each population (must sum to 1)
frac: [0.75, 0.25]

##########################################
# Transfert Function for rate model
##########################################
# set to 0 for threshold linear, 1 for sigmoid
TF_TYPE: 'relu'
# threshold
THRESH: [0.0, 0.0]

##########################################
# Dynamics of the rates
##########################################
# set to 0 if instantaneous rates, 1 if exponentially decaying
RATE_DYN: 1
# rate time constants
TAU: [0.2, 0.1]

# adding rate noise for diffusion
RATE_NOISE: 0
VAR_RATE: 0.0

##########################################
# Dynamics of the recurrent inputs
##########################################
# set to 0 if instantaneous, 1 if exponentially decaying
SYN_DYN: 0
# Synaptic time constants for each population
TAU_SYN: [0.2, 0.1]

##########################################
# NMDA currents
#########################################
IF_NMDA: 0
R_NMDA: 1.0
TAU_NMDA: [0.80, 0.40]

####################
# Plasticity
####################
IF_STP: 1
USE: [0.05]
TAU_FAC: [0.5]
TAU_REC: [0.2]
J_STP: 1.0
STP_TYPE: 'markram'

##########################################
# Feedforward inputs
##########################################
# External inputs strengths
Ja0: [2.0, 1.0]
# External rate
M0: 1.0
# Variance of the noise
VAR_FF: [.1, .1]

##########################################
# Synaptic strengths
##########################################
# Network's gain
GAIN: 0.75
# Synaptic strengths
Jab: [1.0, -1.5, 1, -1]

##############
# Connectivity
##############
# None, full, semi
SPARSE: 0
# seed for connectivity None or float
SEED: 1
# CON_TYPE can be 'all2all' or 'sparse'
CON_TYPE: 'sparse'
# PROBA_TYPE can be 'cosine', 'cosine_spec' or 'lr'
PROBA_TYPE: ['None', 'None', 'None', 'None']

##########
# Low rank
##########
LR_TRAIN: 1
LR_TYPE: 'rand'
TRAIN_SCALE: 'all'

CLAMP: 1

LR_MN: 1
LR_INI: 1.0
LR_UeqV: 1

RANK: 2

IF_OPTO: 0
N_OPTO: 25

SAVE_PATH: '../models/dual/accu'
# SAVE_PATH: '../models/dual/accu'
# SAVE_PATH: '../models/dual/full_UeqV'
# SAVE_PATH: '../models/dual/rand_UeqV'
